// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlcWNiEw_TOPsen0pJzYdPWbc9lskVl74',
    appId: '1:21222061786:web:63cb043a045a297ab797e3',
    messagingSenderId: '21222061786',
    projectId: 'taro-tea',
    authDomain: 'taro-tea.firebaseapp.com',
    storageBucket: 'taro-tea.firebasestorage.app',
    measurementId: 'G-BDXMW4D4Z9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW0w-MCYnv_QqVZb8BtHf7p28rACMdhuc',
    appId: '1:21222061786:android:0a24570345d619a4b797e3',
    messagingSenderId: '21222061786',
    projectId: 'taro-tea',
    storageBucket: 'taro-tea.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqxzmSW5ctOEkS-YVxCXAx2Seas2kYQA4',
    appId: '1:21222061786:ios:14ee124b876c6d80b797e3',
    messagingSenderId: '21222061786',
    projectId: 'taro-tea',
    storageBucket: 'taro-tea.firebasestorage.app',
    iosBundleId: 'com.tarotea.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqxzmSW5ctOEkS-YVxCXAx2Seas2kYQA4',
    appId: '1:21222061786:ios:14ee124b876c6d80b797e3',
    messagingSenderId: '21222061786',
    projectId: 'taro-tea',
    storageBucket: 'taro-tea.firebasestorage.app',
    iosBundleId: 'com.tarotea.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAlcWNiEw_TOPsen0pJzYdPWbc9lskVl74',
    appId: '1:21222061786:web:40a6ccefc233d719b797e3',
    messagingSenderId: '21222061786',
    projectId: 'taro-tea',
    authDomain: 'taro-tea.firebaseapp.com',
    storageBucket: 'taro-tea.firebasestorage.app',
    measurementId: 'G-V7Q29LL2CK',
  );

}